name: Setup commitizen CLI
description: Github action to only configure cz CLI

inputs:
  version:
    description: "Version of commitizen to install"
    required: false
    default: "latest"
  extra_requirements:
    description: "Install extra dependencies"
    required: false
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset. Passed directly to setup-python"

branding:
  icon: "anchor"
  color: "purple"

runs:
  using: "composite"
  steps:
    - id: set-vars
      uses: actions/github-script@v8
      env:
        COMMITIZEN_VERSION: ${{ inputs.version }}
        CACHE: ${{ inputs.cache }}
      with:
        script: |
          // Set commitizen version
          const commitizenVersion = process.env.COMMITIZEN_VERSION || '';
          const setCommitizenVersion = commitizenVersion === 'latest' ? '' : `==${commitizenVersion}`;

          // Write outputs
          core.setOutput('commitizen-version', setCommitizenVersion);
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install commitizen
      shell: bash
      env:
        COMMITIZEN_VERSION: ${{ steps.set-vars.outputs.commitizen-version }}
        EXTRA_REQUIREMENTS: ${{ inputs.extra_requirements }}
      run: |
        python -m pip install -U commitizen${COMMITIZEN_VERSION} ${EXTRA_REQUIREMENTS}
