on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to trigger"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.version }}
      - name: Trigger other job
        run: |
          echo "Version: ${{ inputs.version }}"
