# YES, YOU CAN COPY-PASTE THIS ACTION AND IT SHOULD WORK
# keep in mind, that it won't trigger other actions because it's using action permissions.
# You can: use a PAT token or a workflow_call to trigger another action
on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: commitizen-tools/setup-cz@main
        with:
          python-version: "3.x"
      - id: bump-version
        run: |
          cz bump --yes --annotated-tag
          git push --follow-tags
          current_version="$(cz version -p)" # ATTENTION: You may have to add the v* at the beginning of the version
          echo "current_version=$current_version" >> $GITHUB_OUTPUT
      - name: Build changelog for Release
        env:
          CURRENT_VERSION: ${{ steps.bump-version.outputs.current_version }}
        run: |
          cz changelog --dry-run "${CURRENT_VERSION}" > .changelog.md
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ".changelog.md"
          tag_name: ${{ steps.bump-version.outputs.current_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
